// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcRXxLt5OoL_WhnzCH25puhSB0rtNdBAg',
    appId: '1:433884624359:web:c89b4be763332eeb1df942',
    messagingSenderId: '433884624359',
    projectId: 'call-logs-a024b',
    authDomain: 'call-logs-a024b.firebaseapp.com',
    databaseURL: 'https://call-logs-a024b-default-rtdb.firebaseio.com',
    storageBucket: 'call-logs-a024b.appspot.com',
    measurementId: 'G-B5FXSF67CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlhK6g78uhgu7AGHT6yxpugBImcnz9ZwQ',
    appId: '1:433884624359:android:695a0b67d74d5ad21df942',
    messagingSenderId: '433884624359',
    projectId: 'call-logs-a024b',
    databaseURL: 'https://call-logs-a024b-default-rtdb.firebaseio.com',
    storageBucket: 'call-logs-a024b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Bw2yaZ8vicWQRYuM15SqsVAG6hlOHf8',
    appId: '1:433884624359:ios:a28f3b97ae515f171df942',
    messagingSenderId: '433884624359',
    projectId: 'call-logs-a024b',
    databaseURL: 'https://call-logs-a024b-default-rtdb.firebaseio.com',
    storageBucket: 'call-logs-a024b.appspot.com',
    iosClientId: '433884624359-2p8u0m66vvv83bqu490jdblpu1bheohr.apps.googleusercontent.com',
    iosBundleId: 'com.example.callLogs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Bw2yaZ8vicWQRYuM15SqsVAG6hlOHf8',
    appId: '1:433884624359:ios:a28f3b97ae515f171df942',
    messagingSenderId: '433884624359',
    projectId: 'call-logs-a024b',
    databaseURL: 'https://call-logs-a024b-default-rtdb.firebaseio.com',
    storageBucket: 'call-logs-a024b.appspot.com',
    iosClientId: '433884624359-2p8u0m66vvv83bqu490jdblpu1bheohr.apps.googleusercontent.com',
    iosBundleId: 'com.example.callLogs',
  );
}
